version: "3.8"
services:
  db:
    image: postgis/postgis:latest
    container_name: artur_db
    environment:
      POSTGRES_USER: ${POSTGIS_USER}
      POSTGRES_PASSWORD: ${POSTGIS_PASSWORD}
      ALLOW_IP_RANGE: ${ALLOW_IP_RANGE}
      POSTGRES_DB: ${POSTGIS_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ARTUR"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: .
    container_name: artur_server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://postgres:123456@db:5432/ARTUR"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm start"

  dev:
    build: .
    container_name: artur_dev
    depends_on:
      - server
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run dev"

volumes:
  db_data:
